"""Integration test for brotli content handling."""

import asyncio
import time
import gzip
import zlib
from unittest.mock import AsyncMock, Mock, patch, MagicMock
from concurrent.futures import ThreadPoolExecutor

import pytest
import aiohttp

from src.aibotto.tools.web_fetch import WebFetchTool
from src.aibotto.config.headers_config import COMMON_HEADERS


def test_brotli_dependency_available():
    """Test that brotli library is properly installed and available."""
    try:
        import brotli
        # Test basic functionality
        test_data = b"test data for brotli compression"
        compressed = brotli.compress(test_data)
        assert len(compressed) > 0
        decompressed = brotli.decompress(compressed)
        assert decompressed == test_data
    except ImportError:
        pytest.fail("brotli library is not available")


def test_accept_encoding_not_manually_set():
    """Test that Accept-Encoding is not manually set in COMMON_HEADERS."""
    # Accept-Encoding should be handled automatically by aiohttp
    assert "Accept-Encoding" not in COMMON_HEADERS


def test_web_fetch_tool_headers_configuration():
    """Test that WebFetchTool uses the correct headers configuration."""
    tool = WebFetchTool()
    headers = tool._get_headers()
    
    # Accept-Encoding should be automatically generated by aiohttp based on available decompressors
    # We don't manually set it, so it should contain all supported encodings including brotli if available
    assert "User-Agent" in headers
    assert "Accept" in headers
    assert "Accept-Language" in headers
    
    # aiohttp will automatically add Accept-Encoding with supported encodings
    # when making the actual HTTP request


@pytest.mark.asyncio
async def test_brotli_error_no_longer_occurs():
    """Test that the original brotli error no longer occurs with the fix."""
    
    import aiohttp
    
    # Verify that aiohttp has compression capabilities
    assert hasattr(aiohttp, 'ClientSession')
    
    # Test real HTTP endpoints to verify automatic brotli handling works
    async with aiohttp.ClientSession() as session:
        # Test gzip endpoint (should work)
        try:
            import aiohttp
            async with session.get('https://httpbin.org/gzip', timeout=aiohttp.ClientTimeout(total=10)) as resp:
                assert resp.status == 200
                content = await resp.read()
                assert len(content) > 0
                print("✓ Gzip compression handling works")
        except Exception as e:
            pytest.fail(f"Gzip test failed: {e}")
        
        # Test brotli endpoint (should work with automatic handling)
        try:
            async with session.get('https://httpbin.org/brotli', timeout=aiohttp.ClientTimeout(total=10)) as resp:
                assert resp.status == 200
                content = await resp.read()
                assert len(content) > 0
                print("✓ Brotli compression handling works")
        except Exception as e:
            pytest.fail(f"Brotli test failed: {e}")
    
    # This validates that the new approach is correct
    # aiohttp now automatically handles brotli content negotiation and decompression
    # The brotli dependency ensures automatic brotli support


def test_web_fetch_tool_comprehensive():
    """Comprehensive test of WebFetchTool with automatic brotli support."""
    tool = WebFetchTool()
    headers = tool._get_headers()
    
    # Verify basic headers are present
    required_headers = ["User-Agent", "Accept", "Accept-Language", "DNT"]
    for header in required_headers:
        assert header in headers, f"Missing required header: {header}"
    
    # Verify Accept-Encoding is NOT manually set (aiohttp handles it)
    assert "Accept-Encoding" not in headers, "Accept-Encoding should not be manually set"
    
    # Verify User-Agent looks like a browser
    assert "Mozilla" in headers["User-Agent"]
    
    # Verify Accept-Language format
    lang_header = headers["Accept-Language"]
    assert "en" in lang_header
    assert "q=" in lang_header  # Should have quality values
    
    print("✓ WebFetchTool headers configuration is correct")


@pytest.mark.asyncio
async def test_web_fetch_real_brotli_content():
    """Test WebFetchTool with real brotli-compressed content."""
    tool = WebFetchTool()
    
    # Test with a real HTML page that supports brotli (most modern sites do)
    try:
        result = await tool.fetch("https://httpbin.org/html")
        
        # Should successfully fetch content
        assert result is not None
        assert isinstance(result, dict)
        assert "content" in result
        assert len(result["content"]) > 0
        assert "moby" in result["content"].lower() or "perth" in result["content"].lower()
        
        print("✓ WebFetchTool successfully fetches content from brotli-capable servers")
        
    except Exception as e:
        # If this fails, it might indicate a configuration issue
        pytest.fail(f"WebFetchTool content test failed: {e}")


def test_brotli_compression_ratio():
    """Test that brotli provides reasonable compression ratios."""
    import brotli
    
    # Test with various content types
    test_contents = [
        b"Hello World! This is a simple test string.",
        b"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        b"The quick brown fox jumps over the lazy dog.",
    ]
    
    # Test with repetitive content separately (this might expand very short content)
    repetitive_content = b"A" * 1000
    
    for content in test_contents:
        compressed = brotli.compress(content)
        decompressed = brotli.decompress(compressed)
        
        # Verify lossless compression
        assert decompressed == content
        
        # Verify compression ratio (generally should be reasonable for most content)
        compression_ratio = len(compressed) / len(content)
        
        # Very short content might not compress well (can even expand slightly)
        if len(content) > 50:  # Only check ratio for longer content
            assert compression_ratio <= 1.2, f"Content should not expand too much, ratio: {compression_ratio}"
    
    # Test repetitive content separately (should compress very well)
    compressed = brotli.compress(repetitive_content)
    decompressed = brotli.decompress(compressed)
    assert decompressed == repetitive_content
    
    compression_ratio = len(compressed) / len(repetitive_content)
    assert compression_ratio < 0.8, f"Repetitive content should compress well, ratio: {compression_ratio}"
    
    print("✓ Brotli compression ratios are reasonable")